### ISSUE TITLE
cache - design the merge buffer to allow multiple writes to same cl (after write miss)

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/fpga_mafia#121]
Make sure not to allocate a new entry when core2cache request matches the existing cl address in tq.
- Use the merge buffer to write the new data.
- let the pipe know not to send fm fill. (due to the hit in the merge buffer)
- in case of read after write.
- set the "rd" bit on the merge buffer so that when the fill eventually enters the pipe, it will continue to the cache2core response.

**Comment by amichai-bd** [comment]
Make sure we have a test for this,
Please comment here what is test name for this scenario.
if we don't have it - create it and make sure it behaves as expected.

**Comment by noamsabb** [comment]
The test we wrote for this scenario 


![Image](https://user-images.githubusercontent.com/83982485/222719429-50864b4f-1d22-471b-8d1a-29ecdf2916b2.png)


We can see from the pipe_trk on this test that the fill cancel is not working/enable and we get a fill for the others write and read request even if we are on the same CL


![Image](https://user-images.githubusercontent.com/83982485/222719817-c2fbe5c1-e5de-4e9b-9534-a5352d822746.png)



Also it look like the merge buffer is not getting update like it would after every write miss and it look like its erasing the old values of the write misses instead of keeping them in the mb

**Comment by noamsabb** [comment]
We would have wanted only one fill to happen, to bring the actual CL from FM and for every write_req to write their data to the mb 


![Image](https://user-images.githubusercontent.com/83982485/222725291-ce16e26a-0f2a-4726-996c-04742d7b7cbb.png)



instead of that we can see that the second fill in line 19 (that is not supposed to happen) erased the data wrote in the mb when the first wr miss happen

Also the second fill is for address 1010c so it is for the last wr_req not even the second one

I noticed we didn't added signal for wr_req_hit_mb like we did for rd_req so i tried to add them and adding the same features that we added for rd_req_hit_mb but it still not resolving the problem

**Comment by amichai-bd** [comment]
Please push your changes to your branch so I can review it..
