### ISSUE TITLE
fifo_arb-  valid_arb to the arbiter isn't good

### ISSUE THREAD

**Issue by yeonatanPerelman** [amichai-bd/fpga_mafia#269]
the valid arb should help the RR to choose the next winner to pop. not a general valid_arb.

![image](https://github.com/amichai-bd/fpga_mafia/assets/111231093/b46996cd-92fb-41df-a8f0-d0dd2935d758)

**Comment by amichai-bd** [comment]
I will note the with this current implementation, we found in the router test a case that a transaction is "lost".. we had a typo in the TB where the "ready" was stock at 0. And the fifo arb was pushed & popped, but the transaction never came out due to the wrong use of valid_arb.

The way the arb need to work is a round Robin with a "mask" on the candidates.


1. Please create a test that holds the ready low, and only after couple of cycles releases it back to high - this test will fail due to he bug described.
2. Once we have the failing test, we will work on the RTL fix - re writing the RR with the correct mask.

**Comment by amichai-bd** [comment]
The RTL was already fixed in the branch "abd_fix_fifo_arb_ready_logic"
Please create the test - make sure we fail, then merge the abd_fix_fifo_arb_ready_logic branch and see if it passes
